services:
  - type: web
    name: frontend-azuralis-project-int-platform
    env: static
    buildCommand: cd web && npm ci && npm run build
    staticPublishPath: ./web/dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
